main: prevent scripts from running as root

diff --git a/scripts/pgetinker-stage2 b/scripts/pgetinker-stage2
--- a/scripts/pgetinker-stage2
+++ b/scripts/pgetinker-stage2
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+if [ "$EUID" -eq 0 ]; then
+    echo "Error: This script must not be run as root."
+    exit 1
+fi
+
 UNAMEOUT="$(uname -s)"
 
 # Verify operating system is supported...
